version: '3.4'

x-include:
  commanderserver: &commanderserver
    image: kin3303/commanderserver:${TAG}
    restart: always
    ports:
      - 8000
    volumes:
      - ${PWD}/data/plugins:/opt/electriccloud/electriccommander/plugins
      - ${PWD}/data/workspace:/opt/electriccloud/electriccommander/workspace
      - ${PWD}/data/conf:/opt/electriccloud/electriccommander/conf
      - ${PWD}/scripts:/tmp/scripts
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 180
    labels:
        - "interlock.hostname=commanderserver"
        - "interlock.domain=local"      

  commanderapache: &commanderapache
    image: kin3303/commanderapache:${TAG}
    restart: always
    volumes:
      - ${PWD}/data/plugins:/opt/electriccloud/electriccommander/plugins
      - ${PWD}/data/workspace:/opt/electriccloud/electriccommander/workspace

  commanderagent: &commanderagent
    image: kin3303/commanderagent:${TAG}
    restart: always
    volumes:
      - ${PWD}/data/plugins:/opt/electriccloud/electriccommander/plugins
      - ${PWD}/data/workspace:/opt/electriccloud/electriccommander/workspace

  commanderrepository: &commanderrepository
    image: kin3303/commanderrepository:${TAG}
    restart: always
    volumes:
      - ${PWD}/data/plugins:/opt/electriccloud/electriccommander/plugins
      - ${PWD}/data/workspace:/opt/electriccloud/electriccommander/workspace
      - ${PWD}/data/repository-data:/opt/electriccloud/electriccommander/repository-data

services:
  db:
     image: mysql:5.7
     volumes:
       - ${PWD}/data/db-data:/var/lib/mysql
       - ${PWD}/data/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ecdb
       MYSQL_DATABASE: ecdb
       MYSQL_USER: ecdb
       MYSQL_PASSWORD: ecdb
     hostname: db

  zookeeper1:
    image: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    #volumes:
    #  - ${PWD}/data/zoo/zookeeper1:/data
    hostname: zookeeper1

  zookeeper2:
    image: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    #volumes:
    #  - ${PWD}/data/zoo/zookeeper2:/data
    hostname: zookeeper2
    
  zookeeper3:
    image: zookeeper
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    #volumes:
    #  - ${PWD}/data/zoo/zookeeper3:/data
    hostname: zookeeper3
    
  interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    volumes:
        - ${PWD}/data/interlock/config.toml:/etc/interlock/config.toml
        - ${PWD}/data/interlock/haproxy.cfg.template:/usr/local/etc/interlock/haproxy.cfg.template
        - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    image: haproxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 8443:8443
      - 1936:1936
    volumes:
      - ${PWD}/data/haproxy/:/usr/local/etc/haproxy/
    labels:
        - "interlock.ext.name=haproxy"
    links:
        - interlock:interlock
    depends_on:
        - interlock
        - commanderserver

  commanderserver:
    << : *commanderserver
    depends_on:
      - db
      - zookeeper1
    links:
      - db

  commanderapache:
    <<: *commanderapache
    depends_on:
      - commanderserver

  localagent:
    <<: *commanderagent
    depends_on:
      - commanderserver

  repository:
    <<: *commanderrepository
    depends_on:
      - commanderserver    

